swagger: '2.0'
info:
  title: Monit API
  version: '1.0'
host: 'localhost:5000'
schemes:
  - http
paths:
  /reports:
    get:
      summary: Get all reports
      responses:
        200:
          description: A list of reports
          schema:
            type: array
            items:
              $ref: '#/definitions/Report'
  /reports/{input_report_id}:
    get:
      summary: Get a report by ID
      parameters:
        - name: input_report_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: A single report
          schema:
            $ref: '#/definitions/Report'
        404:
          description: Report not found
definitions:
  Report:
    type: object
    properties:
      id:
        type: string
      content:
        type: string
